#Spring Configuration
spring.application.name=discord-voice-bot
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.mvc.problemdetails.enabled=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:voice_tracker_db}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASS:botsenhateste}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Flyway Migrations
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG

