# ID do seu servidor de testes do Discord
discord.guild.test-id=${GUILD_TEST_ID}

# Em modo dev, podemos querer ver tudo o que o Hibernate faz no banco
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true